name: Web Deploy

on:
  push:
    # Update branch according from where you will be pushing the code
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_REPO: https://github.com/Woukie/RankEverything-WebDeploy.git

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      - name: Push Build
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "build/web/."
          destination_repo: "Woukie/RankEverything-WebDeploy"
          user_email: "lucaseldon@live.com"
          user_name: "Woukie"
          commit_message: "Bot deploy"
